version: '3'

services:
  web:
    build: web/
    restart: always
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/