version: '3'

services:
  web:
    build: web/
    restart: always
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/