version: '3'

services:
  web:
    build: web/
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    volumes:
      - ./web/static:/usr/src/web/static
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    ports:
      - 80:80
    volumes:
      - ./web/static:/usr/src/web/static
    depends_on:
      - web

  db:
    image: postgres:12.0-alpine
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - ./.env.db