# Generated by Django 3.1.7 on 2021-03-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=15, verbose_name='chat_id')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=150, verbose_name='Номер телефона')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь telegram',
                'verbose_name_plural': 'Пользователи telegram',
                'ordering': ['-update_date'],
            },
        ),
    ]
