# Generated by Django 3.1.7 on 2021-05-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_question',
            field=models.TextField(blank=True, verbose_name='Последний заданный вопрос'),
        ),
    ]
