# Generated by Django 3.1.7 on 2021-05-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_telegramuser_last_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Никнейм'),
        ),
    ]
