# Generated by Django 3.1.7 on 2021-03-11 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request_manager', '0002_auto_20210311_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='request_manager.requeststatus', verbose_name='Статус'),
        ),
    ]
