# Generated by Django 3.1.7 on 2021-03-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_API', '0002_botinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botinfo',
            name='platform',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bot_API.botplatform', verbose_name='Платформа'),
        ),
    ]
