# Generated by Django 3.1.7 on 2021-03-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_API', '0003_auto_20210312_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botinfo',
            name='platform',
            field=models.CharField(choices=[('tg', 'telegram'), ('vk', 'Вконтакте')], max_length=80, verbose_name='Платформа'),
        ),
        migrations.DeleteModel(
            name='BotPlatform',
        ),
    ]
