# Generated by Django 3.1.7 on 2021-03-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на бота')),
                ('start_message', models.TextField(blank=True, verbose_name='Стартовое сообщение')),
                ('help_message', models.TextField(blank=True, verbose_name='Сообщение с помощью')),
                ('about_message', models.TextField(blank=True, verbose_name='Описание чат-бота')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_API.botplatform', unique=True, verbose_name='Платформа')),
            ],
            options={
                'verbose_name': 'Чат-бот',
                'verbose_name_plural': 'Чат-боты',
                'ordering': ['title'],
            },
        ),
    ]
