# Generated by Django 3.1.7 on 2021-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_API', '0004_auto_20210312_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.TextField(choices=[('start', 'Стартовое сообщение'), ('help', 'Сообщение с помощью'), ('about', 'Описание чат-бота')], max_length=150, verbose_name='Тип команды')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Команду бота',
                'verbose_name_plural': 'Команды бота',
                'ordering': ['-update_date'],
            },
        ),
        migrations.DeleteModel(
            name='BotInfo',
        ),
    ]
