# Generated by Django 3.1.7 on 2021-03-11 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_manager', '0003_auto_20210311_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='editor',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
    ]
