# Generated by Django 3.1.7 on 2021-04-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_manager', '0006_auto_20210403_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
