# Generated by Django 3.1.7 on 2021-04-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manager', '0010_auto_20210404_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=37, unique=True, verbose_name='Категория'),
        ),
    ]
