# Generated by Django 3.1.7 on 2021-04-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_manager', '0013_auto_20210404_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
