# Generated by Django 3.1.7 on 2021-04-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_manager', '0003_auto_20210311_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesthistory',
            name='tg_user',
        ),
        migrations.RemoveField(
            model_name='requesthistory',
            name='vk_user',
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='phone_number',
            field=models.CharField(default='', max_length=150, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='question',
            field=models.TextField(default='', verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
