# Generated by Django 3.1.7 on 2021-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_manager', '0004_auto_20210412_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='status',
            field=models.CharField(choices=[('Отвечено', 'Отвечено'), ('Ожидает', 'Ожидает')], max_length=150, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='RequestStatus',
        ),
    ]
