# Generated by Django 3.1.7 on 2021-05-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_manager', '0008_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='editor',
        ),
    ]
